version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  mysql:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    container_name: mysql
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database 
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Mount the sql directory into the container
    command: --init-file /docker-entrypoint-initdb.d/init.sql  # Execute the init.sql script during container initialization

